// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucdqqwdzkabtrkyqiomg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZHFxd2R6a2FidHJreXFpb21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDIzNjIsImV4cCI6MjA3MjkxODM2Mn0.tGu0JEKc0wM7HaagMWfVO4kQdvpb_X0VhrQtoF_GDzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});